import { chromium } from "playwright";
const b = await chromium.launch({ headless: true });
const errs = [];
const p = await b.newPage({ viewport: { width: 1500, height: 950 } });
p.on("pageerror", e => errs.push(e.message.slice(0,130)));
await p.goto("http://127.0.0.1:4646/vault", { waitUntil: "networkidle" });
await p.waitForTimeout(2500);
const rows = () => p.locator('aside [title]').count();
console.log("  rows shown (of 262 folders):", await rows());
const exp = p.locator('button[aria-expanded="false"]');
console.log("  expandable:", await exp.count());
const before = await rows();
await exp.first().click(); await p.waitForTimeout(600);
console.log(`  expand -> ${before} to ${await rows()} rows`);
await p.locator('button[aria-expanded="true"]').first().click(); await p.waitForTimeout(500);
console.log(`  collapse -> ${await rows()} rows`);
const f = p.getByPlaceholder("Filter folders");
await f.fill("client"); await p.waitForTimeout(700);
console.log("  filter 'client' matches:", await rows());
await f.fill("zzzznope"); await p.waitForTimeout(500);
console.log("  no-match empty state:", await p.getByText("No folder matches.").count() > 0);
console.log(errs.length ? "  ERRORS " + [...new Set(errs)].join(" | ") : "  no page errors");
await b.close();
