/**
 * A real Obsidian plugin, generated into the vault.
 *
 * Most people who would want Lore already have their wiki open in Obsidian all
 * day. Asking them to switch to another app to see what their agents wrote is
 * asking them to remember a second place, which means they check it on the days
 * they were already going to check it — the same failure the brief has without
 * a notification.
 *
 * So Lore goes to them. This is a complete plugin: a manifest and one file of
 * plain JavaScript that talks to the local API. It deliberately does not bundle
 * anything, has no build step and no dependencies, because a plugin that needs
 * npm to install is a plugin that does not get installed.
 *
 * Everything it does is read-only against Lore, and it never writes to the
 * vault. The one thing it must never do is fail loudly: if Lore is not running,
 * every command says so once and does nothing, because a notes app that throws
 * errors because a different app is closed is worse than no integration.
 */

export const PLUGIN_ID = "lore";

export function manifest(version = "1.0.0"): string {
  return JSON.stringify(
    {
      id: PLUGIN_ID,
      name: "Lore",
      version,
      minAppVersion: "1.4.0",
      description:
        "What your agents learned, and answers from your own wiki — from the local Lore app.",
      author: "Lore",
      isDesktopOnly: true,
    },
    null,
    2,
  );
}

export function mainJs(port = 4646): string {
  return `'use strict';

/*
 * Lore for Obsidian.
 *
 * Talks to the Lore app on 127.0.0.1 and nothing else. No network calls leave
 * the machine, no data is uploaded, and the vault is never written to.
 *
 * Generated by Lore. Regenerating overwrites this file.
 */

const { Plugin, ItemView, Notice, MarkdownRenderer, Modal, Setting } = require('obsidian');

const BASE = 'http://127.0.0.1:${port}';
const VIEW_TYPE = 'lore-brief';

async function api(path, init) {
  // A short timeout on purpose: Lore being closed must feel like "not running",
  // not like Obsidian hanging.
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 8000);
  try {
    const response = await fetch(BASE + path, { ...init, signal: controller.signal });
    if (!response.ok) throw new Error('Lore returned ' + response.status);
    return await response.json();
  } finally {
    clearTimeout(timer);
  }
}

const OFFLINE = 'Lore is not running. Open the Lore app and try again.';

class BriefView extends ItemView {
  getViewType() { return VIEW_TYPE; }
  getDisplayText() { return 'Lore brief'; }
  getIcon() { return 'newspaper'; }

  async onOpen() {
    this.render();
  }

  async render() {
    const root = this.containerEl.children[1];
    root.empty();
    root.createEl('h3', { text: 'What your agents learned' });
    const status = root.createEl('p', { text: 'Reading…' });

    let data;
    try {
      data = await api('/api/brief?days=1&mark=0');
    } catch (error) {
      status.setText(OFFLINE);
      return;
    }

    if (!data.items || !data.items.length) {
      status.setText('Nothing was written today.');
      return;
    }
    status.setText(data.events + ' writes across ' + data.pagesTouched + ' pages.');

    const list = root.createEl('div');
    for (const item of data.items) {
      const row = list.createEl('div', { cls: 'lore-item' });
      row.style.padding = '8px 0';
      row.style.borderTop = '1px solid var(--background-modifier-border)';

      const line = row.createEl('div', { text: item.line });
      line.style.cursor = 'pointer';
      line.onclick = () => this.openPage(item.relPath);

      const meta = row.createEl('div', { text: item.title + (item.agent ? ' · ' + item.agent : '') });
      meta.style.fontSize = '12px';
      meta.style.color = 'var(--text-muted)';
    }
  }

  /*
   * Opening the real note, not a copy.
   *
   * The whole value of being inside Obsidian is that a brief line leads to the
   * file you already know how to edit. A page Obsidian cannot find is reported
   * rather than silently doing nothing — it means the vault open here is not
   * the one Lore is watching, which is worth knowing.
   */
  async openPage(relPath) {
    const file = this.app.vault.getAbstractFileByPath(relPath);
    if (!file) {
      new Notice('That page is not in this vault. Is Lore watching a different folder?');
      return;
    }
    await this.app.workspace.getLeaf(false).openFile(file);
  }
}

class AskModal extends Modal {
  constructor(app) {
    super(app);
    this.question = '';
  }

  onOpen() {
    const { contentEl } = this;
    contentEl.createEl('h3', { text: 'Ask your wiki' });

    new Setting(contentEl)
      .setName('Question')
      .addText((text) => {
        text.setPlaceholder('What did I decide about…');
        text.onChange((value) => { this.question = value; });
        text.inputEl.style.width = '100%';
        text.inputEl.addEventListener('keydown', (event) => {
          if (event.key === 'Enter') this.run();
        });
        window.setTimeout(() => text.inputEl.focus(), 0);
      });

    this.answerEl = contentEl.createEl('div');
    this.answerEl.style.marginTop = '12px';

    new Setting(contentEl).addButton((button) =>
      button.setButtonText('Ask').setCta().onClick(() => this.run()),
    );
  }

  async run() {
    if (!this.question.trim()) return;
    this.answerEl.setText('Thinking…');
    let data;
    try {
      data = await api('/api/ask', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ question: this.question }),
      });
    } catch (error) {
      this.answerEl.setText(OFFLINE);
      return;
    }

    this.answerEl.empty();
    if (!data.answer) {
      this.answerEl.setText(data.reason || 'No answer came back.');
      return;
    }

    await MarkdownRenderer.renderMarkdown(data.answer, this.answerEl, '', this);

    // Confidence is stated separately, never folded into the prose: when
    // retrieval is unsure the model still writes fluently, and a fluent
    // paragraph is indistinguishable from a certain one.
    if (typeof data.confidence === 'number' && data.confidence < 0.35) {
      const warn = this.answerEl.createEl('p', {
        text: 'Retrieval was not confident — treat these as leads and check the sources.',
      });
      warn.style.color = 'var(--text-muted)';
      warn.style.fontSize = '12px';
    }

    if (data.passages && data.passages.length) {
      const sources = this.answerEl.createEl('p', {
        text: 'Sources: ' + data.passages.slice(0, 6).map((p) => p.relPath).join(', '),
      });
      sources.style.color = 'var(--text-muted)';
      sources.style.fontSize = '12px';
    }
  }

  onClose() { this.contentEl.empty(); }
}

module.exports = class LorePlugin extends Plugin {
  async onload() {
    this.registerView(VIEW_TYPE, (leaf) => new BriefView(leaf));

    this.addRibbonIcon('newspaper', 'Lore brief', () => this.showBrief());

    this.addCommand({
      id: 'lore-brief',
      name: "Show today's brief",
      callback: () => this.showBrief(),
    });

    this.addCommand({
      id: 'lore-ask',
      name: 'Ask your wiki',
      callback: () => new AskModal(this.app).open(),
    });

    this.addCommand({
      id: 'lore-related',
      name: 'Related pages to this note',
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file) return false;
        if (checking) return true;
        this.showRelated(file);
        return true;
      },
    });
  }

  async showBrief() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE);
    if (existing.length) {
      this.app.workspace.revealLeaf(existing[0]);
      existing[0].view.render();
      return;
    }
    const leaf = this.app.workspace.getRightLeaf(false);
    await leaf.setViewState({ type: VIEW_TYPE, active: true });
    this.app.workspace.revealLeaf(leaf);
  }

  async showRelated(file) {
    try {
      const data = await api('/api/semantic?related=' + encodeURIComponent(file.path));
      const related = (data.results || []).slice(0, 6).map((r) => r.relPath || r.id);
      new Notice(related.length ? 'Related:\\n' + related.join('\\n') : 'Nothing related found.');
    } catch (error) {
      new Notice(OFFLINE);
    }
  }

  onunload() {
    // Leaves are not detached here: Obsidian's own guidance is that a plugin
    // tearing down its views on unload loses the user's layout on every update.
  }
};
`;
}
